# -*- coding: utf-8 -*-
"""UTS_PDT_NO2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ojMHPbC1OLRfVqlw4-scdYSbRxResm9w
"""

import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.patches as patches

df = pd.read_csv("https://raw.githubusercontent.com/robbyhdayatt/UTS-PDT/main/Dataset%20Nomor%202.csv")

print(df)

fig, ax = plt.subplots(figsize=(12, 8))

box_size = 0.5

terisi = df[df['Status'] == 'Terisi']['Nomor_Bangku']
for seat in terisi:
    row = ord(seat[0]) - ord('A')
    col = int(seat[1:]) - 1
    rect = patches.Rectangle((col, row), box_size, box_size, linewidth=1, edgecolor='r', facecolor='r')
    ax.add_patch(rect)

kosong = df[df['Status'] == 'Kosong']['Nomor_Bangku']
for seat in kosong:
    row = ord(seat[0]) - ord('A')
    col = int(seat[1:]) - 1
    rect = patches.Rectangle((col, row), box_size, box_size, linewidth=1, edgecolor='g', facecolor='g')
    ax.add_patch(rect)

ax.set_xticks(range(10))
ax.set_xticklabels([str(i) for i in range(1, 11)])
ax.set_yticks(range(10))
ax.set_yticklabels(['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J'])

ax.set_xlabel('Nomor Bangku')
ax.set_ylabel('Baris')
ax.set_title('Tata Letak Kursi Terisi dan Kosong di Bioskop')

ax.set_xlim([-0.5, 9.5])
ax.set_ylim([-0.5, 9.5])

plt.gca().invert_yaxis()
plt.grid(True)
plt.show()

bangku_terisi = df[df['Status'] == 'Terisi']
bangku_kosong = df[df['Status'] == 'Kosong']

print("Bangku yang Terisi:")
print(bangku_terisi)
print("\nBangku yang Kosong:")
print(bangku_kosong)